SET IDENTITY_INSERT [dbo].[Categories] ON
INSERT INTO [dbo].[Categories] ([CategorieID], [CategorieNom]) VALUES (1, N'Soleil')
INSERT INTO [dbo].[Categories] ([CategorieID], [CategorieNom]) VALUES (2, N'Mi-ombre')
INSERT INTO [dbo].[Categories] ([CategorieID], [CategorieNom]) VALUES (3, N'Ombre')
INSERT INTO [dbo].[Categories] ([CategorieID], [CategorieNom]) VALUES (4, N'Palmier')
INSERT INTO [dbo].[Categories] ([CategorieID], [CategorieNom]) VALUES (5, N'Fougère')
INSERT INTO [dbo].[Categories] ([CategorieID], [CategorieNom]) VALUES (6, N'Broméliacée')
INSERT INTO [dbo].[Categories] ([CategorieID], [CategorieNom]) VALUES (7, N'Panier suspendu')
INSERT INTO [dbo].[Categories] ([CategorieID], [CategorieNom]) VALUES (8, N'Plante à fleurs')
INSERT INTO [dbo].[Categories] ([CategorieID], [CategorieNom]) VALUES (9, N'Rare')
INSERT INTO [dbo].[Categories] ([CategorieID], [CategorieNom]) VALUES (10, N'Robuste')
INSERT INTO [dbo].[Categories] ([CategorieID], [CategorieNom]) VALUES (11, N'Haute')
INSERT INTO [dbo].[Categories] ([CategorieID], [CategorieNom]) VALUES (12, N'Courte')
INSERT INTO [dbo].[Categories] ([CategorieID], [CategorieNom]) VALUES (13, N'Feuillage de couleur')
INSERT INTO [dbo].[Categories] ([CategorieID], [CategorieNom]) VALUES (14, N'Cactus')
INSERT INTO [dbo].[Categories] ([CategorieID], [CategorieNom]) VALUES (15, N'Plante grasse')
INSERT INTO [dbo].[Categories] ([CategorieID], [CategorieNom]) VALUES (16, N'Arbre')
INSERT INTO [dbo].[Categories] ([CategorieID], [CategorieNom]) VALUES (17, N'Bizarre')
SET IDENTITY_INSERT [dbo].[Categories] OFF
