SET IDENTITY_INSERT [dbo].[Clients] ON
INSERT INTO [dbo].[Clients] ([ClientId], [Adresse], [Cellulaire], [Courriel], [Nom], [Pays], [Prenom], [Province], [Telephone], [Ville]) VALUES (1, N'123 Principale', N'514-333-2222', N'g.crete@cgodin.qc.ca', N'Crete', N'Canada', N'Guillaume', N'Quebec', N'514-222-3333', N'Montreal')
INSERT INTO [dbo].[Clients] ([ClientId], [Adresse], [Cellulaire], [Courriel], [Nom], [Pays], [Prenom], [Province], [Telephone], [Ville]) VALUES (3, N'789 Secondaire', N'514-777-8888', N'j.fbindia@cgodin.qc.ca', N'Bindia', N'Canada', N'Jules Ferry', N'Quebec', N'514-444-3333', N'Montreal')
INSERT INTO [dbo].[Clients] ([ClientId], [Adresse], [Cellulaire], [Courriel], [Nom], [Pays], [Prenom], [Province], [Telephone], [Ville]) VALUES (4, N'345 de la Côte', N'514-666-7777', N'a.mdallaire@cgodin.qc.ca', N'Martial Dallaire', N'Canada', N'Antoine', N'Quebec', N'450-888-9999', N'Laval')
INSERT INTO [dbo].[Clients] ([ClientId], [Adresse], [Cellulaire], [Courriel], [Nom], [Pays], [Prenom], [Province], [Telephone], [Ville]) VALUES (5, N'1234 Esplanade', N'514-876-2222', N'r.jjulien@cgodin.qc.ca', N'Jean Julien', N'Canada', N'Ronald', N'Quebec', N'515-987-1111', N'Laval')
INSERT INTO [dbo].[Clients] ([ClientId], [Adresse], [Cellulaire], [Courriel], [Nom], [Pays], [Prenom], [Province], [Telephone], [Ville]) VALUES (6, N'123 Sesame Street', N'514-765-4321', N'b.bird@cgodin.qc.ca', N'Bird', N'Canada', N'Big', N'Quebec', N'514-123-4567', N'Montreal')
INSERT INTO [dbo].[Clients] ([ClientId], [Adresse], [Cellulaire], [Courriel], [Nom], [Pays], [Prenom], [Province], [Telephone], [Ville]) VALUES (7, N'13 Private Drive', N'514-888-0000', N'b.simson@cgodin.qc.ca', N'Simson', N'Canada', N'Bart', N'Quebec', N'514-999-0000', N'Springfeild')
INSERT INTO [dbo].[Clients] ([ClientId], [Adresse], [Cellulaire], [Courriel], [Nom], [Pays], [Prenom], [Province], [Telephone], [Ville]) VALUES (8, N'555 All American road', N'514-666-6666', N's.smith@cgodin.qc.ca', N'Smith', N'Canada', N'Stan', N'Quebec', N'514-777-7777', N'West Langley')
INSERT INTO [dbo].[Clients] ([ClientId], [Adresse], [Cellulaire], [Courriel], [Nom], [Pays], [Prenom], [Province], [Telephone], [Ville]) VALUES (1002, N'456 Main', N'514-666-2222', N'm.degagne@cgodin.qc.ca', N'De Gagné', N'Canada', N'Marc', N'Quebec', N'514-222-3333', N'Rigeau')
SET IDENTITY_INSERT [dbo].[Clients] OFF
